### ISSUE TITLE
Uni logo popping up unexpectedly 

### ISSUE THREAD

**Issue by patpaev** [marcom-unimelb/unimelb-design-system#150]
Not sure if it's a browser bug (Chrome 39.0.2171.52 beta) , but I've seen it a few times now – can't seem to replicate it, but it usually disappears after a scroll or keypress

![screen shot 2014-11-18 at 3 17 42 pm](https://cloud.githubusercontent.com/assets/6847023/5082528/1bb80280-6f36-11e4-837c-3ed11231a575.png)

**Comment by waitingallday** [comment]
Only seems to happen on Chrome, could be related to 3d transform rendering

**Comment by waitingallday** [comment]
I can't replicate this bug on the current version of design system & Chrome - there were a few changes made to the header that may have fixed this, or given that it was only Chrome and not Safari it may have been a browser bug that they've since fixed.

Feel free to re-open if you experience it again!

**Comment by patpaev** [comment]
:+1:
