### ISSUE TITLE
Maps issue with tabbed nav in CMS

### ISSUE THREAD

**Issue by yevek** [marcom-unimelb/unimelb-design-system#208]
Maps not displaying correctly on initial page load when used in conjunction with tabbed-nav in Squiz CMS.
![maps-tabs-issue-ff](https://cloud.githubusercontent.com/assets/1305804/6590153/1428b078-c800-11e4-8504-c69279694713.png)

Bad URL: http://cms.unimelb.edu.au/mi/home
Browser tested: FF 36.0.1 and Chrome 41.0

When map is used in page with tabbed-nav it displays fine.  
Good URL: http://cms.unimelb.edu.au/mi/contact

**Comment by dkevey** [comment]
NOTE: if you resize browser  http://cms.unimelb.edu.au/mi/home it then shows, but pin is missing.

**Comment by dkevey** [comment]
This also happens on this site http://web.unimelb.edu.au/layouts/about so the issue is not unique to Squiz CMS

![map-issues](https://cloud.githubusercontent.com/assets/1305804/6797495/e01267e6-d256-11e4-984d-1a0adca72016.png)

**Comment by rhyslawry** [comment]
@axelboc @yevek 
Hey guys, just raising this issue again
Has there been any progress in figuring out why maps aren't loading correctly when used in a tab that is not the first tab to load?
There are a number of live sites that this issue is presenting itself on, most commonly ones with a "contact us" tab that includes a map.

**Comment by waitingallday** [comment]
This is likely caused by the google maps js API - we've noticed a few other 3rd party systems will not activate if they are not visible at page load in (as with tabs). A quick fix will be to not use maps on a tabbed layout, or at least not on any later tab, I'm not sure if there is much we can do with this.

**Comment by axelboc** [comment]
Yeah it's quite a complex problem. I believe the solution is to load the Google API asynchronously when the tab is selected, but that's really not trivial, especially if we want to keep things decoupled (i.e. the tabs should not have to know about the maps and vice-versa).

**Comment by waitingallday** [comment]
Oops, I think I just found a way to fix this 😄 Will submit a PR
