### ISSUE TITLE
Image class="inset-left" floating over in-page navigation

### ISSUE THREAD

**Issue by yevek** [marcom-unimelb/unimelb-design-system#224]
When using images in Squiz CMS, it's hard to do more than add a class to align image. This is causing floating/overlapping issues if the browser window isn't quite wide enough. 

It's only an issue with the left aligned images because of the negative margin. 

![image-issues-margin](https://cloud.githubusercontent.com/assets/1305804/6797609/306f80b0-d258-11e4-8452-d992550dc476.png)

**Comment by waitingallday** [comment]
Yeah.. those floating images were designed well before the jump nav existed, at the time we wanted to just exclude them from appearing on the same page (because of that overlap), but never did anything to prevent it within the system.

I'll talk to Andi and see if we can figure something out. For now, I would suggest using the full width images on http://web.unimelb.edu.au/components/media - I know this might not be ideal for portrait aspect images.

**Comment by axelboc** [comment]
Same issue but slightly different behaviour than the previous screenshot:

**Comment by axelboc** [comment]
Just needs some margin I reckon.
