### ISSUE TITLE
Position of images on event blocks

### ISSUE THREAD

**Issue by deanbrobinson** [marcom-unimelb/unimelb-design-system#235]
Images on events blocks are displaying with strange crops.  MCM Today for example, is showing a lot of foreheads:
http://mcm.unimelb.edu.au/

Although it's partly down to the original images used, is there something we can do to improve it? E.g. make them vertically centred?

![screen shot 2015-04-15 at 3 09 25 pm](https://cloud.githubusercontent.com/assets/10523462/7152588/18c8b5c2-e382-11e4-87d0-09368cdd0b90.png)

**Comment by waitingallday** [comment]
I want to say this is more an issue of image selection, those boxes can't really accommodate anything but a landscape image if there is any text at all with it (which there always is).

**Comment by dkevey** [comment]
Hi guys, I've been working on getting events to show in the CMS and I've noticed a few things: 
- in order for the images (in events) to line up correctly the event heading has to be restricted to 2 lines of text (aprox 30 charc) and even if there is only 1 line of text the image is bigger. 
![mcm-events](https://cloud.githubusercontent.com/assets/1305804/7171696/1f87784c-e41f-11e4-9ea8-2c87640f1e8f.png)

- By restricting the event heading the event starts to loose context of what it's about, i.e. the event on MCM for the Melbourne International Trumpet Festival, doesn't show enough information
![melbourne-international](https://cloud.githubusercontent.com/assets/1305804/7171729/7006e76c-e41f-11e4-9353-025add51fff8.png)

What we can do: 
- provide standard images to use (like on events.unimelb) so that they are horizontal and the correct size. 
- create style guides or examples of how to create headings that mean something (in 30 charac) or perhaps if the full event topic is too long, then we don't show the event image?

This is an example showing a calendar event in the CMS next to an event (feed) from event.unimelb (the image from the feed is not the correct size). 

It might be easier for me to show you.
![calendar-event](https://cloud.githubusercontent.com/assets/1305804/7171795/9b898cae-e420-11e4-978b-7188b75d41eb.png)

**Comment by deanbrobinson** [comment]
Thanks (belated) for your ideas on this Donna. We've had a chat about the options to solve this.

So it is just portrait images that are the issue. VCA and MCM events are populated by RSS, which means they have the option to include a differently cropped (landscape) image. So this is a solution for them, for the short term.

In the longer term, we'll be working on a feature in bespoke that gives the ability to upload an alternative image, so a landscape crop can be used for a thumbnail, or the ability to not display a thumbnail, which might be preferable.
