### ISSUE TITLE
Different behaviour if your page's first header is a "bottom-align"

### ISSUE THREAD

**Issue by patpaev** [marcom-unimelb/unimelb-design-system#240]
If a `.bottom-align` header is your first element in the `role=main`, it looks like there are some CSS rules that overwrite what a bottom-align header should look like. 

Here, the `<p>` has no `padding-bottom` because of the "first-child" rule that seems to be taking precedent 
![screen shot 2015-04-23 at 2 59 30 pm](https://cloud.githubusercontent.com/assets/6847023/7290879/e9c2fbb8-e9c9-11e4-93bc-c0970b7b71b2.png)

But if I copy and paste that exact markup again, because it is no longer a "first-child", it appears as it does in the documentation. 

![screen shot 2015-04-23 at 3 01 08 pm](https://cloud.githubusercontent.com/assets/6847023/7290890/2932d674-e9ca-11e4-8fbb-13ee2b553960.png)

**Comment by waitingallday** [comment]
Thanks Pat, I've figured out what happened here - this was caused by style leaking through from the [Simple Header Banner](http://web.unimelb.edu.au/components/headers#simple-header-banner) where it has two paragraph blocks, and the entire thing is centred vertically so you'd never see the problem there.

I'll push through a fix shortly.
