### ISSUE TITLE
jumpnav - request for javascript to be updated

### ISSUE THREAD

**Issue by cigar69** [marcom-unimelb/unimelb-design-system#255]
It would be great to have the jumpnav functionality for pages with H2 to still be available for subpages  under a tab structure. (see attachments)
Using the current functionality on standard page

![standpage_with_jumpnav_turned_on](https://cloud.githubusercontent.com/assets/4565925/7602032/0a1dda5c-f962-11e4-8ac4-5ba3ff58d67e.png)

Using the current functionality in Tab Nav structure

![using_jumpnav_in_tab_structure](https://cloud.githubusercontent.com/assets/4565925/7602033/107e12cc-f962-11e4-9522-7fecd8d5bcef.png)

How I imagine it to look.

![how_it_should_look](https://cloud.githubusercontent.com/assets/4565925/7602034/15be6c82-f962-11e4-8c8a-43365ee5f973.png)

**Comment by waitingallday** [comment]
I'm going to say no to this for now - you have at least 4 completely different (and slightly competitive) navigation methods happening on this page.

I don't want to get preachy (not too preachy :) but you should always remember to think about how anything you do benefits the end user. In this case, the mixture of navs just seem to be exposing the IA, which is something we do not want, ever. IA is the crudest way of guiding a user.

This is a bit off topic, but the way that tabs have been used are a Major Concern for us at the moment - ideally, we'd want no more than 4 and a single word only in the title (personally I would use no more than 3, with less than 10 characters per title). You can see the effect when it gets stacked too much, it wraps to the next line and instead of looking like tabs it now looks like a weird big blue heading. It's worth remembering that one of the most popular resolutions on uni sites is 1366 x 768, so most people are getting that broken view when you over-fill the tabs.

We're not really sure what to do about that right now, but it's not really working. You could say that this is a broken implementation, but it was never intended to be used in this way.

Please do get in contact with me, or Andi (@herrweis) or Dean (@deanbrobinson) if you'd like to talk further!

**Comment by rothenburycam** [comment]
I'd also like to see this fixed as outlined by @cigar69. On the site I'm building, the jump navs are actually overlapping (see attached). 

![screen shot 2015-05-26 at 2 49 41 pm](https://cloud.githubusercontent.com/assets/11714609/7805491/ba929d88-03b6-11e5-87e6-796771abff6b.png)

**Comment by waitingallday** [comment]
I'm going to give the same advice as above: the tabs are used incorrectly on this page. Instead of exposing the IA, think about how you want a visitor to this site to consume the content.

For this bug specifically, the methods used to build the tabs and jump nav both depend on the same mechanism (url #), so on a technical level there is no way to make them both work on the same page. The tab logic could be rewritten, but I can't see that happening for at least a few months - for now it would be best to avoid combinations that don't work!

**Comment by herrweis** [comment]
> I'm going to give the same advice as above: the tabs are used incorrectly on this page. Instead of exposing the IA, think about how you want a visitor to this site to consume the content.
> - @waitingallday 

Full ack! If you ever come to a structure where this could seem like a solution, often the structure itself isn't right. If you stumble across these problems @deanrobinson or me (@herrweis) are happy to help. Just shoot one of us a message!

**Comment by waitingallday** [comment]
In fixing Tom's issue #267, I found that this will work fine within tabs - but only if you're using the split page `aside/.bside` layout as in the [Course example layout](http://web.unimelb.edu.au/layouts/course#course-structure)

Will try to document this a little better on the site.
