### ISSUE TITLE
Request to increase tile background palette for catorgories in filtered-listing-grid

### ISSUE THREAD

**Issue by cigar69** [marcom-unimelb/unimelb-design-system#268]
RE: filtered-listing-grid li.category

Issue 1

The faculty of MDHS has 9 research themes.
Currently research themes beyond the category-e  default to category-a ( see attachment). Can the   tile background palette for categories beyond 'e' be increased?

Issue 2

People have raised the difficulty of reading category-d   with black text layered over the top.
 Can this be reviewed?

.filtered-listing-grid li.category-d a {
1.    background-color: #82a1bd;

![capture](https://cloud.githubusercontent.com/assets/4565925/7905260/aca28dc2-0858-11e5-903b-610db1bf7a64.JPG)

**Comment by waitingallday** [comment]
Issue 1- I completely understand why you ask, but no we don't. Andi will love this, I'm going to refer you to [point 3 on this page](http://web.unimelb.edu.au/designers) - having 9 different colours to represent the themes is convenient, but does it serve the end user? I feel like having all the colours within a single grid will make it harder to read.

@deanbrobinson will have something better to say on this, but my suggestion would be to split the themes vertically down the page (instead of the department filter). I think the theme is more important than the department, for a public-facing user.

Issue 2 - definitely looks a little off in that screen, will look into this!

**Comment by yevek** [comment]
Hi Brendan, I was thinking about using this for research projects, but have the filter to show what is open (green) and what is completed (grey), then using the drop-down to select the topic (theme). I think having too many coloured boxes on the page, makes it look like someone went loose with a paintball gun.
![research projects](https://cloud.githubusercontent.com/assets/1305804/7955163/64c7e340-0a19-11e5-97ca-a2f734058a5b.png)

**Comment by waitingallday** [comment]
This was a really helpful Discussion Point, but I'm marking it as wontfix for now - there are other (better) alternatives available rather than increasing the palette.
