### ISSUE TITLE
Redundant parent links in local nav?

### ISSUE THREAD

**Issue by patpaev** [marcom-unimelb/unimelb-design-system#270]
Taking the example of the sample code, from the way the local nav is implemented, it looks like a list item with sub-sections can never actually be clicked on itself. 

e.g.

![screen shot 2015-06-03 at 1 10 28 pm](https://cloud.githubusercontent.com/assets/6847023/7952036/93c734c4-09f2-11e5-89d5-5056f06f0c85.png)

Are there future plans for these links to be followable, or are they just there for accessibility / SEO reasons?

(I guess it's also a UX question. Presumably, a user isn't specifically looking for "sub-section", they're looking for "A page in the sub-section", but what if there is actually content in the "sub-section" page that they are looking for?)

**Comment by herrweis** [comment]
This is build like it is on purpose. The '/sub-section' cannot be reached via the menu. Only through the breadcrumb. This means that the page should not be filled with important content rather than having a link list to the sub pages. So "/sub-section" should never hold important content. Preferably only a listing to the subpages (http://web.unimelb.edu.au/components/listings)

**Comment by waitingallday** [comment]
You're absolutely right, this is something we always meant, but never documented. I'll add a clarification on the setup page.

**Comment by patpaev** [comment]
Great, I thought that might be the case – just wanted to check!
