### ISSUE TITLE
Listings are not centered

### ISSUE THREAD

**Issue by herrweis** [marcom-unimelb/unimelb-design-system#286]
All listings are not correctly centered

![uneven](https://cloud.githubusercontent.com/assets/2480825/8666510/cacbd674-2a35-11e5-9a06-f3870f1f46c8.jpg)

Because of the percentage values this becomes more relevant the wider the browser window becomes.

A possible fix could be to add a `text-align: center` to the parent ul

**Comment by waitingallday** [comment]
That would work, but will lead to this

![screen shot 2015-07-14 at 4 12 03 pm](https://cloud.githubusercontent.com/assets/863542/8667433/329fd860-2a43-11e5-9c08-d600ed2e5e77.png)

I was using a pretty loose width so that it wouldn't break - 24.5%, should be able to tighten this up a quite a bit. At the same time, I would suggest left-aligning the images to keep a straight line (it only happens at super wide resolutions, but still).

**Comment by herrweis** [comment]
+1 for left align — I didn't think of the possibility that there might be an uneven number of list elements. That was pretty stupid :-)
