### ISSUE TITLE
icons not working in v3.0

### ISSUE THREAD

**Issue by yevek** [marcom-unimelb/unimelb-design-system#304]
tried to implement in next version of MCE and icons not showing. Andi says this is a bug. 

![icons](https://cloud.githubusercontent.com/assets/1305804/9592088/910fd9a2-5083-11e5-95a8-d8e849d04b14.png)

**Comment by waitingallday** [comment]
As it turns out, this was caused by a completely different bug :sweat_smile: 

The inpage navigation (aka jumpnav) was designed to work with a layout that included a `header` as the first semantic element, and if it isn't present, then it breaks the js. I've fixed this now in https://github.com/marcom-unimelb/unimelb-design-system/commit/75b422ee1158c53db60a7521a340230884fc5ed4, and deployed to `v3.0` (CDN users will need to wait up to 24 hrs to see the fix). I will add that this looks a little awkward without the `header` element, since it needs to add an arbitrary clearance above the nav while the header logo is there, then remove it when the page begins scrolling - there's no nice way of making it scroll smoothly via js, so I've set it to jump directly instead. You'll see it!

Anyway, the icons should be fine.
