### ISSUE TITLE
No header with aside content issue with margin-top

### ISSUE THREAD

**Issue by yevek** [marcom-unimelb/unimelb-design-system#421]
We have a template in MCE that has no header and aside content for Research projects. It's only happened since we upgraded from v3.3.1 to v3.4.1

See this page: http://cms.unimelb.edu.au/controlled-environment/templates/research/research-project-page
![no-header-aside-content](https://cloud.githubusercontent.com/assets/1305804/10923285/4899b958-82d4-11e5-93b4-e9f755fc82ab.png)

**Comment by axelboc** [comment]
The problem comes from the extra wrapping `div` inside `with-aside`. If you remove it and place `bside` and `aside` right under `with-aside`, it works fine.

Any chance you could remove the `jumpnav` as well, though? I feel like it might not be needed, and two sidebars just seems a bit much. Also, have you seen the new header-less layout with the blue border at the top: https://web.unimelb.edu.au/layouts/no-header/?

**Comment by axelboc** [comment]
Had a chat with @herrweis and the outcome is that we'll need to come up with a better alternative to this two-sidebar layout, as this one just doesn't work. Especially:

- The new header-less layout with the blue bar breaks.
- The jumpnav sits above the content *and* the sidebar on tablet. Instead, it should sit only above the content so as to let the sidebar reach the header. Unfortunately this is not realistically achievable with the current jumpnav and with-aside markup.

So if you think you can remove either the jumpnav or the sidebar without compromising the user experience, then go for it; otherwise, just leave it as is and with the padding override for now.

**Comment by axelboc** [comment]
Scratch that... :smile:  We'll try to make the two sidebars work by modifying the code that injects the jumpnav.

**Comment by axelboc** [comment]
Closing this now since @yevek removed the jumpnav from the Research layout, leaving only the sidebar.
