### ISSUE TITLE
Client requests for Tabbed Nav Header with text anchors

### ISSUE THREAD

**Issue by rhyslawry** [marcom-unimelb/unimelb-design-system#422]
Recently, during the design and building process for a site (entrepreneurship.unimelb.edu.au), I had a client/stakeholder-side request for a page with a navigation header along the top, which functions like a jumpnav - i.e. scrolls to text anchors within the page

The brief was to create a single-page scrolling site similar to both:
- http://collision.unimelb.edu.au/ - the main/current advertising campaign within unimelb, and
- http://www.unimelb.edu.au/#study - the University's homepage (top right corner)
Which proves that in the past and present the University has a clear need for such a functionality.

The primary use would be for "one-pager" sites with multiple anchors requiring significant scrolling.
The tabbed nav doubling up as a sticky header would be an additional client-desired feature (as seen on Collision.unimelb)

After consultation with the team, we determined that it is currently not possible using the tabbed navigation option in the metadata screen (dynamically created tabs based on immediate children)

However, after further thought, I realised it was in fact possible, and better yet, completely within the specs of the Design System & web.unimelb

My solution is to use an in-page tabbed navigation at the top of the page, as seen on http://web.unimelb.edu.au/components/tabs/
and simply change the `<a href="#tab1">` tags to link to various text anchors within the page
e.g. `<a href="#study">`
- Note: "Use tabbed navigation" is NOT ticked on the metadata screen

Here is my proof-of-concept test page with the same content as Entrepreneurship.unimelb, but styled as a one-pager:
http://about.unimelb.edu.au/strategy-and-leadership/entrepreneurship/test/tab-test/_recache 

**Pros:**
- Uses no custom css, javascript or "hacks"
- Provides elegant alternative to jumpnav
- Obviously fulfils a client need, as it is commonly seen/requested

**Cons/Drawbacks (currently):**
- Paul: Could be confusing for users expecting to open a new tab but instead scrolls to text anchor
- Tabs do not change automatically based on user location within the page - eg. If you click anchor4 and scroll back to the top, anchor4 is still "selected"
- Extra `<p>` tag under header causing whitespace padding (Occurs with "home page light" template, but not with "inside page with blue header" template)
- "Smooth scrolling" down to text anchors doesn't occur with "home page light" template (which would be most commonly requested I'm expecting), but does occur with "inside page with blue header" template

I would love your thoughts on this, and on whether this is a reasonable suggestion for a future addition to the Design System, and/or what to suggest to clients and stakeholders who request this functionality - i.e. is my solution sufficient?

**Comment by herrweis** [comment]
Hey @rhyslawry :

Thanks for all the work you've put into this! Great work! However, in most cases (as seen in your example as well) it is a structural content problem rather than a navigational one. The tabs (and consequently their behaviour) are purposed for exactly what you have here. Different sections target different audiences and should therefore not be shown on the same page. This helps the user to find quickly what they are after and singles out content that is not relevant to them.
As a result, you can offer the user more relevant content in each section.

I am aware that single page layouts (and the smooth scroll) are very attractive to stakeholders, but they are often not the best choice. The collision website was not done by our team and they did not use the design system at all. And it shows one particular problem with one pagers: They load a whopping 4.5 MB at once, because everything lives within this one page. We are currently working on a new homepage for the University which does not use the scrolling system of the current one: you can find a very early prototype: http://ui-prototypes.s3-website-ap-southeast-2.amazonaws.com/pages/home/

Furthermore, the tab navigation does not adapt to the page's scroll position. That means that a user does not know where they are within the page. It has to be sticky at the top and show precisely in which section the user is. This is not supported by the current tabs.

The example page feels very dense and I, as a user, have troubles finding the right section. There are (understandably) call to action buttons in every section, but I have no clear guidance where to look. I have to read everything to understand which one is the right for me.

I would recommend to use the tabs with their standard behaviour, because it will cause less confusion for the user and additionally gives you the opportunity to tailor more content to the specific target audiences.

Again, awesome work and a good idea! I know that it is sometimes hard to handle stakeholder requests, but in this case I would not proceed with this solution (if possible).

**Comment by rhyslawry** [comment]
Thanks for all that feedback @herrweis , that's brilliant

I forgot to mention, we actually ended up going with the tabbed layout as you suggested, as the preferred solution out of the two options - Jumpnav one-pager vs. tabbed multi-page

The clients seemed a little disappointed that we couldn't reproduce collision-style navigation, instead opting for the multi-page tabbed layout, but given the brief I knew that the jumpnav alternative would be disliked even more so.

The final result can be viewed here: http://about.unimelb.edu.au/strategy-and-leadership/entrepreneurship

Thanks again!

**Comment by axelboc** [comment]
It looks really nice, congrats! I reckon the single-page solution would have looked very confusing indeed. 

Quick suggestion, not related: have you tried wrapping the call-to-actions inside `<section>` elements to give them a bit more space?

I'll close this issue now.
