### ISSUE TITLE
Spacing gone missing

### ISSUE THREAD

**Issue by woowoowoo** [marcom-unimelb/unimelb-design-system#481]
Clemmie Wetherall has noted a problem on her page at: http://students.fvas.unimelb.edu.au/research-higher-degrees/candidature-and-milestones/code-of-conduct-and-intellectual-property (and others), where the spacing top and bottom of the main content area has vanished, and looks crowded.
Page is standard Controlled Environment template.
Looks like a deliberate part of the Design System, what needs to be done to remedy the issue?

**Comment by yevek** [comment]
FYI Axel/Jason it only seems to be an issue when jumpnav is used.

**Comment by axelboc** [comment]
A few potential solutions:

- move the jumpnav up so it is the first child of the `div` with `role="main"`
- wrap the lead and content `div` in a section element
- try using the new `lead left` variant
- switch to the new headerless layout with `<h1 class="aligned-title">` instead of `<header>` and `<section class="lead left">`
- wait for MCE to be upgraded to the next release as I will try to replicate the MCE layouts in the design system and make sure they all work.

**Comment by tomstringer** [comment]
Hi Axel

Looks like the latest update has brought this issue back. @gilesng has reported they've lost the padding on this page: http://cms.unimelb.edu.au/controlled-environment/chemistry/engage/chemistry-outreach-program

Padding returns when jumpnav is removed. 

![screen shot 2016-04-18 at 2 01 27 pm](https://cloud.githubusercontent.com/assets/924501/14593465/16377f78-056e-11e6-9c6c-c40681893ffc.png)

**Comment by axelboc** [comment]
I don't think I ever "fixed" the issue per se.

The **lead left** variant will fix the spacing: `<section class="lead left">...</section>`, but the page would also need to be updated to the new headerless layout: `<h1 class="aligned-title">...</h1>` instead of `<header><h1>...</h1></header>`

**Comment by gilesng** [comment]
This variant does work on pages with the jump nav.

Cheers

Giles  (c:=

On 18/04/2016 2:16 pm, Axel Bocciarelli wrote:
>
> I don't think I ever "fixed" the issue per se.
>
> The *lead left* variant will fix the spacing: |<section class="lead 
> left">...</section>|, but the page would also need to be updated to 
> the new headerless layout: |<h1 class="aligned-title">...</h1>| 
> instead of |<header><h1>...</h1></header>|
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub 
> <https://github.com/marcom-unimelb/unimelb-design-system/issues/481#issuecomment-211193240>
>


-- 

*Giles Ng**|*  Web Project Lead

Academic Engagement Team, Faculty of Science

The University of Melbourne, Victoria 3010 Australia

*T: *+61 3 8344 9029 *E: *gilesng@unimelb.edu.au 
<mailto:gilesng@unimelb.edu.au>

facebook.com/melbuni <http://facebook.com/melbuni> *| 
twitter.com/unimelb <http://twitter.com/unimelb>| *unimelb.edu.au 
<http://www.unimelb.edu.au/>

This email and any attachments may contain personal information or 
information that is otherwise confidential or the subject of copyright. 
Any use, disclosure or copying of any part of it is prohibited. The 
University does not warrant that this email or any attachments are free 
from viruses or defects. Please check any attachments for viruses and 
defects before opening them. If this email is received in error please 
delete it and notify us by return email.
