### ISSUE TITLE
request for Flickr added to icon set

### ISSUE THREAD

**Issue by gyounger** [marcom-unimelb/unimelb-design-system#508]
Hi, just a friendly request for flickr icon to be added to icon set here:
http://web.unimelb.edu.au/components/icons/
To be used it in social media footer
thanks :)
Gav

**Comment by axelboc** [comment]
Adding an icon is always a bit contentious as it adds weight to the design system, and therefore to every site that uses it. Brand icons are particularly tricky, since there are so many of them. Flickr, Tumblr, Pinterest, WhatsApp, Google Plus, Vimeo, Vine etc. A limit has to be set somewhere.

A couple of solutions to consider:
- Is the Flickr option really needed? Does it add significant value for the majority of your users?
- Could you use a more generic icon, like `world` or `share`?

**Comment by patpaev** [comment]
Considering services like Flickr and Vimeo are used widely throughout the University, an argument could be made to include those two icons (and the opposite for Vine and Tumblr).

However, For Flickr specifically, the identity of its logo relies on its two 'brand' colours (blue and pink), but the icons in the Design System have no inherent colour. This means the icon would end up looking like this: 

<img src="https://cloud.githubusercontent.com/assets/6847023/12251279/d137c664-b921-11e5-897b-4a73a39bebe8.jpg" width="128" />

And this is kind of tricky because it's not really recognisable on its own as anything, plus it could be confused with a ['more'](https://design.google.com/icons/#ic_more_horiz) or 'ellipsis' icon.

**Comment by patpaev** [comment]
**Update: (and probably digressing a bit much...)** I just checked out [Flickr's home page](https://www.flickr.com/) and the "dots icons" is nowhere to be found (with the exception of the favicon)

Are they moving away from this logo altogether in favour of the wordmark?

**Comment by axelboc** [comment]
As discussed, the icon won't be added. As a workaround, the use of custom icons was documented as part of the [v3.9 release](https://github.com/marcom-unimelb/unimelb-design-system/releases/tag/v3.9).
