### ISSUE TITLE
Padding needed under tables

### ISSUE THREAD

**Issue by simpsonatti** [marcom-unimelb/unimelb-design-system#530]
There is no padding underneath tables, which is making them sit on the footer. Example here : 
![screen shot 2016-02-02 at 12 03 50 pm](https://cloud.githubusercontent.com/assets/17016472/12736523/11a9e0b8-c9a5-11e5-9ada-8d8c09a9a7a6.png)
Thanks

**Comment by simpsonatti** [comment]
`<footer></footer>` is a solution to this problem but is there another way around this by modifying the CSS to accommodate tables at the bottom of a page?

**Comment by waitingallday** [comment]
Hi, sorry I'm not sure who I'm talking to. There are two ways to fix this with the system at present, as you mentioned adding in a `footer` will add padding below and is a legitimate, semantic solution. The other is to wrap the table in a `section` within the main body since that has padding built in, but this may cause trouble if you're using a full-width table - the example above doesn't seem to, though.

We've avoided having padding directly on elements, and tried to keep this on wrappers instead (like the section), to keep our options open for future component combinations.

**Comment by simpsonatti** [comment]
Thanks for the reply. It's Helen from the Staff Hub team. Having to add code is not ideal for future maintenance by Edit + users, but understand the need to keep it open in future.

**Comment by waitingallday** [comment]
Thanks Helen, I'm going to close this issue for now, but I definitely see your point with CMS - we're always wary of adding classes and markup that may not be easy to do for CMS users! We're looking at redoing the way components are spaced in a future update.
