### ISSUE TITLE
Maintainer and authoriser information

### ISSUE THREAD

**Issue by ptagell** [marcom-unimelb/unimelb-design-system#9]
In the current templates, we have the concept of a local footer. In this local footer often people put information about who to contact if something is wrong or incorrect, or who has authorised the site.

This is also where we often put general contact details for a site and I have even seen this space used as a secondary mega-footer. 

Often, this info is out of date and not really that useful. That said, it does seem to be a requirement as it's used to do much of our site classification and ownership. 

As I see it, there are several possible solutions. 

1. We provide a local footer component
2. We provide a better alternative for people to use that covers all these uses (eg. a "site metadata type link that opens a small modal with this info). 
3. We find a way to integrate this into the local navigation so that it can be made accessible, but not always visible. 

![screenshot_4_03_2014_11_09_am-3](https://f.cloud.github.com/assets/150315/2316283/3ea637b6-a331-11e3-964b-5ad2d6fc31a0.png)

Any thoughts?

**Comment by uomben** [comment]
How about an expandable footer div labelled something along the lines of "about this page".  I think it at least needs to be visible on the page as  a link and not tucked away in the local nav. Definitely needs to be just the page metadata and not the other stuff that people squeeze in there.

**Comment by waitingallday** [comment]
I think we could move move a named div down below the footer, same way the breadcrumbs are managed.

Any thoughts, @herrweis ?

**Comment by herrweis** [comment]
yes, a local footer is needed - I don't know about the meta information though. Is that really useful for any user (except uni - internally)? However, I do like the idea of a permanent feedback ("Report a problem with this page") link.

**Comment by dkevey** [comment]
This is an example of our "Authoriser" and "Maintainer" for each page, including the date this was last updated. For those of us in Faculty land dealing with 50+ web maintainers, this is important and necessary. 

For those of us using the Squiz CMS we use "Metadata Schemas" to create an manage assets across our sites. See attached screenshots.

![authoriser maintainer](https://cloud.githubusercontent.com/assets/1305804/6590437/08815668-c804-11e4-988a-376c8a5dcc2d.png)

![metdata](https://cloud.githubusercontent.com/assets/1305804/6590467/885549e4-c804-11e4-91c8-e1b6b033ba0d.png)

**Comment by herrweis** [comment]
Thanks Donna! That is exactly what I was guessing — it is needed for internal use rather than the general public. Wouldn't the meta tags be a better place?

**Comment by dkevey** [comment]
I also include them in the head section, including the user's name that last updated the asset. 

However, displaying the authoriser and maintainer's details (including date updated) is part of governance that we use to determine; 
a) if we need the page in the first place (if we don't have a maintainer then it won't be added)
b) if it hasn't been updated for a year, then it helps my case to remove it.

I believe it's also helpful for the user to determine if the correct is accurate or not, and until we have a single source of truth, less websites and less maintainers - I believe we still need it (at least on our Faculty sites).

I'm currently reviewing our Faculty site and I'm using this information to determine if we keep it or archive it.

![meta2](https://cloud.githubusercontent.com/assets/1305804/6590519/c3792134-c805-11e4-986f-f0a050fbe8cd.png)

**Comment by deanbrobinson** [comment]
I don't think we should display information we rely on internally to audit our content. Especially fields such as authoriser and maintainer.

**Comment by dkevey** [comment]
Do you have a better suggestion to review 8,000 assets for 50+ web maintainers? you guys can either design something pretty or live with the style that I will need to create.

**Comment by yevek** [comment]
FYI - I am using this style on footer of our sites in CMS, unless you guys want to come up with something better I am happy with this for the moment http://cms.unimelb.edu.au/mi/research
![footer](https://cloud.githubusercontent.com/assets/1305804/7955263/3d42823e-0a1a-11e5-9877-bcc47126a173.png)

**Comment by deanbrobinson** [comment]
Hey @yevek, before we look at this for either just your site or the templates in general, it would be good to break down exactly what content is absolutely necessary. For the design system, we're rationalising every (yes every!) piece of content that appears on a page to make sure it delivers to a user need.

Here I can see there's the authoriser's title, authoriser's department, maintainer title, maintainer email address, date created, time created, last modified date, last modified time. It would really help us to work this out if we can determine each user need. E.g. As a [e.g. FBE staff member] I need to know if a page was last updated over a year ago, so that I can remove it etc.

I'm happy to work on this with you, shouldn't take us too long.

**Comment by rothenburycam** [comment]
**bump!**

Just wondering if there's any update on this? One advantage for the user being able to access this content is they have someone to contact when there's a problem with the content, but I think Dean's point about serving a back end purpose is totally valid.

**Comment by yevek** [comment]
Hi @rothenburycam we've had extensive discussions about this. In a coming update to MCE we will be parsing this info through the Design file so it will be available in code (for the moment), so stay tuned for this one.

**Comment by uomben** [comment]
A few thoughts.
If you need metadata visible on the page for admin functions I'd say you have serious efficiency problems with admin processes. When the UoM metadata schema first came out it was clear that it had a purpose, but we didn't have the tools to make use of the metadata so a) it didn't serve that purpose and b) (because of that) data quality was generally poor because no one could be bothered updating the metadata.

I've been thinking about the tools I'd developed for managing static sites and whether or not I should rebuild them for our CMS site. Looking at it from a data management perspective, I think it would be feasible to create some useful management tools outside of the CMS provided it was easy enough to sync the metadata. An asset listing with all of the admin metadata as an XML feed would be extremely useful for this and opens up a range of possibilities without requiring any modifications/tweaking of the CMS.

Which then brings us back to what really needs to be in the footer.  I could be cynical and say that it doesn't really matter because the pages are so long with the new design that no one's going to get to the bottom of the page...  but that wouldn't be very helpful. ;-)   Screw what we want to see... any admin metadata should be in the header as a metadata field, not just a comment so that it can be harvested more easily.  That brings it down to a) what the user needs to see and b) any compliance-related metadata.  My pet hates with the footer are things like clicking on a Facebook/Twitter icon on a department's page and going to the uni's Facebook/Twitter feed.... or seeing the mega footers where you get the departmental version of the footer and then the global one.  With the controlled environment there is the possibility of having a more practical mix of global and local metadata/stuff in the footer without relinquishing control of the globally-required bits.  IMO the design should focus on this. Trying to force a global header on other systems via injection is counter productive.  Required elements and design should be enforced by policy with balls and a big stick.

**Comment by waitingallday** [comment]
Going to close this old one off, most of this discussion is no longer relevant.
